#!/usr/bin/env python

import re
import sys

id_p = re.compile("^[0-9]{3} ")
fpr_p = re.compile("[A-Z0-9 ]+")
uid_p = re.compile("^uid ")

id = "000"

idx = 0

for line in sys.stdin:
    if id_p.match(line):
        id = line[0:3]
        idx = 0
    elif fpr_p.match(line):
        fpr = line.replace(" ", "").strip()
    elif uid_p.match(line):
        uid = line[5:].strip()
        if uid[0] != "[":
            print("%s_%d %s %s" % (id, idx, fpr, uid))
            idx = idx + 1


